server:
  port: 7777

spring:
  # 数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/stray_animals_management_system?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: root
      password: 123456
      initial-size: 10
      max-active: 30
      min-idle: 5
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      static-locations: classpath:/resources/

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.HexTechGDUT.entity.po


# aliyun.oss.file.endpoint=oss-cn-shenzhen.aliyuncs.com
# aliyun.oss.file.keyid=LTAI5tKz4Pn4Rjw8xYN5Wp4b
# aliyun.oss.file.keysecret=D3c0IfghhPj0de7aqahSn0tTGd7mW7
# aliyun.oss.file.bucketname=se-byflandre